version: '3'

services:
  nodeapp:
   image: csparth/codelashes_node
   ports:
     - 7700:7700
   deploy:
     replicas: 15
     restart_policy:
       max_attempts: 3
       condition: on-failure       
     update_config:
       parallelism: 3
       delay: 10s
   networks: 
    - balance 
  
  proxy:
    image: csparth/loadbalancer_nginx
    ports:
      - 5000:80
    depends_on:
      - nodeapp
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - balance

networks:
  balance:
    driver: overlay