version: '3.8'

services:
  nodeapp:
    image: csparth/codelashes_node
    ports:
      - 7700:7700 
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 3
        delay: 10s
    networks:
      - balance
  
  proxy:
    image: csparth/loadbalancer_nginx
    ports:
      - 5000:80 
    depends_on:
      - nodeapp
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - balance

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"      # Redis port
      - "8001:8001"      # RedisInsight port
    volumes:
      - redis_data:/data
    networks:
      - balance
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      # Removed the worker constraint as it might be causing issues

volumes:
  redis_data:

networks:
  balance:
    driver: overlay